# Generated by Django 5.0.2 on 2024-02-28 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Message_likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='date posted')),
                ('post', models.TextField(max_length=200)),
                ('like', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='room.message_likes')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=200)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('hosts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='room.hosts')),
                ('messages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='room.messages')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='room.users')),
            ],
        ),
    ]
