# Generated by Django 5.0.2 on 2024-02-28 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('question', '0001_initial'),
        ('suggestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='suggestion.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account'),
        ),
        migrations.AddField(
            model_name='question_likes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account'),
        ),
        migrations.AddField(
            model_name='question',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='question.question_likes'),
        ),
        migrations.AddField(
            model_name='question_response',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account'),
        ),
        migrations.AddField(
            model_name='question',
            name='responses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='question.question_response'),
        ),
        migrations.AddField(
            model_name='question_response_likes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account'),
        ),
        migrations.AddField(
            model_name='question_response',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='question.question_response_likes'),
        ),
    ]
