# Generated by Django 5.0.2 on 2024-02-28 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('blog', '0001_initial'),
        ('suggestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='suggestion.category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account'),
        ),
        migrations.AddField(
            model_name='blog_comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account'),
        ),
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='blog.blog_comment'),
        ),
        migrations.AddField(
            model_name='blog_comment_likes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account'),
        ),
        migrations.AddField(
            model_name='blog_comment',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='blog.blog_comment_likes'),
        ),
        migrations.AddField(
            model_name='blog_likes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account'),
        ),
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='blog.blog_likes'),
        ),
    ]
