# Generated by Django 5.0.2 on 2024-02-28 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Enter Category(min 20 letters)', max_length=30, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion_likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(help_text='Enter response(min 200 letters)', max_length=200, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='date posted')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(help_text='Enter suggestion(min 200 letters)', max_length=200, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='date posted')),
                ('status', models.CharField(blank=True, choices=[('PE', 'Pending'), ('PR', 'Processing'), ('CO', 'Completed'), ('WA', 'Watching'), ('CG', 'Considering'), ('UP', 'Upcoming'), ('DI', 'Dismissed')], default='PE', help_text='States of the sugesstion', max_length=40)),
                ('approved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='suggestion.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account')),
                ('like', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='suggestion.suggestion_likes')),
                ('responses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='suggestion.suggestion_response')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion_Response_likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.account')),
            ],
        ),
        migrations.AddField(
            model_name='suggestion_response',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='suggestion.suggestion_response_likes'),
        ),
    ]
